Improve logs and add timeouts
platzio/backend pull request #67
Opened 2023-08-13 12:56 UTC by ayalash

2023-08-13 13:45 UTC, vmalloc requested changes

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +        Ok(exe_result) => {
```
result.map(|exe_result| {
   debug!(...);
   exe_result.output
}.tap_err(...)

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +async fn create_interval_stream(duration: Duration) -> IntervalStream {
Doesn't have to be `async`

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +    let mut timeout_timer_stream = create_interval_stream(timeout_duration).await;
I think this should be a `sleep`

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +        |phase_name: &str| -> bool { phase_name == "Succeeded" || phase_name == "Failed" };
I would change to eq_ignore_ascii_case

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +        |p| p == "Running" || is_pod_finished(p),
Same here

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +            "Failed waiting for Helm pod {} to reach Running phase",
Interpolate variable here

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +        debug!("Attaching to pod {}", pod_name);
Interpolate variable

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +            debug!("{} deletion failed", pod_name);
Interpolate variables

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +            debug!("{} deletion succeed", pod_name);
Interpolate variables

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +                "Failed waiting for Helm pod {} to reach Succeeded or Failed phase",
Interpolate variables

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +    info!("Pod {} terminated (phase: {})", pod_name, pod_phase);
Interpolate variables

2023-08-13 13:45 UTC, vmalloc commented on k8s-agent/src/k8s/pods.rs
> +        |p| p == "Running" || is_pod_finished(p),
Why not unite these three conditions? Maybe call it `pod_not_pending`?

2023-08-16 13:28 UTC, ayalash commented
@vmalloc Fixed.
Please review

2023-08-17 16:18 UTC, popen2 approved these changes

2023-08-17 16:18 UTC, merged